name: ci

on: pull_request

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14]
        angular-version: [10.0.x, 11.0.x, 11.1.x, 11.2.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v3
        with:
          angular-version: ${{ matrix.angular-version }}
      - name: install
        run: npm install
      - name: build
        run: npm run build -- --skip-nx-cache
      - name: test
        run: npm run test -- --ci --code-coverage
